# this file is to enable claude code
services:
  service:
    # override included service
    build:
      target: dev-claude
    # workaround for oauth callback bug
		# https://github.com/anthropics/claude-code/issues/9376#issuecomment-3900547326
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ${CLAUDE_CONFIG_USER_DIR:-~/.claude}:/home/vscode/.claude
